version: 2.1

orbs:
  sonar: hubci/sonar@1.0.0
  cimg-rlang-orb: circleci/cimg-orb@0.1.4

workflows:
  main:
    jobs:
      - cimg-rlang-orb/build-and-deploy:
          image: cimg/rlang
          context: cimg-rlang-publishing
